development:
  adapter: postgresql
  database: amazonasin_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: amazonasin_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: amazonasin_production
  pool: 5
  timeout: 5000